import type { DomainEvent } from "@skald/event-bus";
import type { ActionIntentCommand } from "@skald/intent-parser";
import { commandEventId } from "./ids.js";

/**
 * Command Handler (infra, NOT a Rule — AGENTS invariant #7, §9.9).
 *
 * - Does NOT receive ReadonlyWorld and has no access to game state.
 * - Performs ONLY structural validation (known command type, required fields
 *   present). No gameplay decisions, no wall checks, no time checks.
 * - Produces exactly one Domain Event:
 *     valid   → ActionAttempted (payload: normalized intent + raw text)
 *     invalid → CommandRejected (payload: { reason })
 * - The event is the root of its chain: causationId === null.
 *
 * `correlationId` is generated by the caller (CLI), one per top-level command.
 * `timestamp` is the current world.time passed in by the caller (an integer
 * counter — never Date.now()).
 */
export function handleCommand(
  command: ActionIntentCommand,
  correlationId: string,
  timestamp: number,
): DomainEvent {
  const base = {
    schemaVersion: 1,
    timestamp,
    correlationId,
    causationId: null,
  };

  // Validate required fields
  if (!command.type || command.type !== "ActionIntentCommand") {
    const eventId = commandEventId(correlationId, "CommandRejected");
    return {
      ...base,
      eventId,
      type: "CommandRejected",
      payload: { reason: `invalid command type: ${command.type}` },
    };
  }

  if (!command.mode || !command.operation) {
    const eventId = commandEventId(correlationId, "CommandRejected");
    return {
      ...base,
      eventId,
      type: "CommandRejected",
      payload: { reason: "missing mode or operation" },
    };
  }

  const eventId = commandEventId(correlationId, "ActionAttempted");
  return {
    ...base,
    eventId,
    type: "ActionAttempted",
    payload: {
      mode: command.mode,
      operation: command.operation,
      target: command.target ?? null,
      secondaryTarget: command.secondaryTarget ?? null,
      instrument: command.instrument ?? null,
      manner: command.manner ?? null,
      goal: command.goal ?? null,
      utterance: command.utterance ?? null,
      rawText: command.rawText,
      interpretation: command.interpretation,
    },
  };
}
