import type { DomainEvent } from "@skald/event-bus";
import type { PlayerCommand } from "@skald/intent-parser";
import { commandEventId } from "./ids.js";

/**
 * Command Handler (infra, NOT a Rule — AGENTS invariant #7, §9.9).
 *
 * - Does NOT receive ReadonlyWorld and has no access to game state.
 * - Performs ONLY structural validation (known command type, required fields
 *   present). No gameplay decisions, no wall checks, no time checks.
 * - Produces exactly one Domain Event:
 *     valid   → MoveRequested (payload: { direction })
 *     invalid → CommandRejected (payload: { reason })
 * - The event is the root of its chain: causationId === null.
 *
 * `correlationId` is generated by the caller (CLI), one per top-level command.
 * `timestamp` is the current world.time passed in by the caller (an integer
 * counter for MVP-0 — never Date.now()).
 */
export function handleCommand(
  command: PlayerCommand,
  correlationId: string,
  timestamp: number,
): DomainEvent {
  const base = {
    schemaVersion: 1,
    timestamp,
    correlationId,
    causationId: null,
  };

  if (command.type === "MoveCommand") {
    const eventId = commandEventId(correlationId, "MoveRequested");
    return {
      ...base,
      eventId,
      type: "MoveRequested",
      payload: { direction: command.direction },
    };
  }

  const eventId = commandEventId(correlationId, "CommandRejected");
  return {
    ...base,
    eventId,
    type: "CommandRejected",
    payload: { reason: `unknown command type: ${command.type}` },
  };
}