import type { DomainEvent } from "@skald/event-bus";
import type { ActionIntentCommand, InteractionCommand, JourneyIntent } from "@skald/intent-parser";
import { commandEventId } from "./ids.js";
import { isKnownInteractionVerb } from "./interaction-registry.js";
import { handleResourceExtractionCommand } from "./resource/commands.js";
import type { ResourceExtractionCommand } from "./resource/commands.js";

/**
 * Command Handler (infra, NOT a Rule — AGENTS invariant #7, §9.9).
 *
 * - Does NOT receive ReadonlyWorld and has no access to game state.
 * - Performs ONLY structural validation (known command type, required fields
 *   present). No gameplay decisions, no wall checks, no time checks.
 * - Produces exactly one Domain Event:
 *     InteractionCommand → InteractionRequested (canonical v1 path, ADR-0013)
 *     valid ActionIntentCommand → ActionAttempted (legacy verbs only)
 *     invalid → CommandRejected (payload: { reason })
 * - The event is the root of its chain: causationId === null.
 *
 * `correlationId` is generated by the caller (CLI), one per top-level command.
 * `timestamp` is the current world.time passed in by the caller (an integer
 * counter — never Date.now()).
 */
export function handleCommand(
  command: ActionIntentCommand | InteractionCommand | JourneyIntent | ResourceExtractionCommand,
  correlationId: string,
  timestamp: number,
): DomainEvent {
  const base = {
    schemaVersion: 1,
    timestamp,
    correlationId,
    causationId: null,
  };

  // Validate required fields
  const commandType = (command as { type?: unknown }).type;
  if (commandType !== "ActionIntentCommand" && commandType !== "InteractionCommand" && commandType !== "JourneyIntent" && commandType !== "ResourceExtractionCommand") {
    const eventId = commandEventId(correlationId, "CommandRejected");
    return {
      ...base,
      eventId,
      type: "CommandRejected",
      payload: { reason: `invalid command type: ${String(commandType)}` },
    };
  }

  if (command.type === "ResourceExtractionCommand") {
    return handleResourceExtractionCommand(command, correlationId, timestamp);
  }

  if (command.type === "JourneyIntent") {
    const destination = command.destination?.raw.trim() ?? "";
    if (destination.length === 0) {
      return {
        ...base,
        eventId: commandEventId(correlationId, "CommandRejected"),
        type: "CommandRejected",
        payload: { reason: "missing journey destination" },
      };
    }
    return {
      ...base,
      eventId: commandEventId(correlationId, "JourneyRequested"),
      type: "JourneyRequested",
      payload: {
        destination,
        routeHint: command.routeHint?.raw ?? null,
        rawText: command.rawText,
      },
    };
  }

  if (command.type === "InteractionCommand") {
    if (!isKnownInteractionVerb(command.verb)) {
      return {
        ...base,
        eventId: commandEventId(correlationId, "CommandRejected"),
        type: "CommandRejected",
        payload: { reason: `unknown interaction verb: ${command.verb}` },
      };
    }
    const object = command.target?.raw.trim() ?? "";
    // observe/listen may describe the surroundings without a named target;
    // all other v1 verbs require a concrete target.
    const allowsNoTarget = command.verb === "observe" || command.verb === "listen";
    if (object.length === 0 && !allowsNoTarget) {
      return {
        ...base,
        eventId: commandEventId(correlationId, "CommandRejected"),
        type: "CommandRejected",
        payload: { reason: "missing interaction object" },
      };
    }
    return {
      ...base,
      eventId: commandEventId(correlationId, "InteractionRequested"),
      type: "InteractionRequested",
      payload: {
        verb: command.verb,
        object,
        instrument: command.instrument?.raw ?? null,
        location: null,
        modifiers: [],
      },
    };
  }

  if (!command.mode || !command.operation) {
    const eventId = commandEventId(correlationId, "CommandRejected");
    return {
      ...base,
      eventId,
      type: "CommandRejected",
      payload: { reason: "missing mode or operation" },
    };
  }

  const eventId = commandEventId(correlationId, "ActionAttempted");
  return {
    ...base,
    eventId,
    type: "ActionAttempted",
    payload: {
      mode: command.mode,
      operation: command.operation,
      target: command.target ?? null,
      secondaryTarget: command.secondaryTarget ?? null,
      instrument: command.instrument ?? null,
      manner: command.manner ?? null,
      goal: command.goal ?? null,
      utterance: command.utterance ?? null,
      rawText: command.rawText,
      interpretation: command.interpretation,
    },
  };
}
